"""Rebuild immutable v1 ranks: deterministic void-and-cluster on eligible sites.
No libraries required. Periodic Gaussian uses physical candidate-site spacing.
Seed 1729, sigma 1.5 geometric-mean lattice units; stable index tie-breaking.
"""
import math
from pathlib import Path
N = 32
COUNT = N*N

def generate(sx, sy):
    sigma = 1.5 * math.sqrt(sx*sy)
    kernel = [math.exp(-((min(x,N-x)*sx)**2+(min(y,N-y)*sy)**2)/(2*sigma*sigma)) for y in range(N) for x in range(N)]
    rows = [[kernel[((j//N-i//N)%N)*N+(j%N-i%N)%N] for j in range(COUNT)] for i in range(COUNT)]
    state = 1729
    order = list(range(COUNT))
    for i in range(COUNT-1,0,-1):
        state = (1664525*state+1013904223)&0xffffffff
        j = state%(i+1)
        order[i],order[j] = order[j],order[i]
    active = set(order[:COUNT//10])
    energy = [sum(rows[i][j] for i in active) for j in range(COUNT)]
    def change(i, sign):
        for j, value in enumerate(rows[i]): energy[j] += sign*value
        if sign == 1: active.add(i)
        else: active.remove(i)
    def cluster(): return max(sorted(active), key=lambda i: energy[i])
    def void(): return min((i for i in range(COUNT) if i not in active),key=lambda i: energy[i])
    for _ in range(COUNT*10):
        i = cluster(); change(i,-1)
        j = void(); change(j,1)
        if i == j: break
    else: raise RuntimeError('Relaxation failed')
    initial = active.copy()
    ranks = [0]*COUNT
    for rank in range(len(active)-1,-1,-1):
        i = cluster(); ranks[i] = rank; change(i,-1)
    for i in sorted(initial): change(i,1)
    for rank in range(len(active),COUNT//2):
        i = void(); ranks[i] = rank; change(i,1)
    # Dense half: remove clusters of holes, assigning increasing ranks.
    holes = set(range(COUNT))-active
    active.clear(); energy[:] = [0]*COUNT
    for i in sorted(holes): change(i,1)
    for rank in range(COUNT//2,COUNT):
        i = cluster(); ranks[i] = rank; change(i,-1)
    assert sorted(ranks) == list(range(COUNT))
    return ranks

text = '// Generated by tools/generate-artistic-ranks.py. Immutable v1; seed 1729.\n'
for name, sx, sy in [('ARTISTIC_SQUARE_RANKS',2,2),('ARTISTIC_ROW_RANKS',4,1)]:
    ranks = generate(sx,sy)
    text += f'export const {name}: readonly number[] = [\n'
    text += '\n'.join('  '+','.join(map(str,ranks[i:i+N]))+',' for i in range(0,COUNT,N))+'\n];\n'
Path('packages/conversion-core/src/artistic-ranks.ts').write_text(text)
