// @ts-check
"use strict";
// ============================================================================
// Next LoRes ASM Export — sjasmplus SAVENEX source for LoRes 128×96 pictures
// ============================================================================

/**
 * Generates sjasmplus-compatible ASM source for ZX Spectrum Next LoRes display.
 * Programs the ULA palette via NEXTREG $43/$40/$44, enables LoRes via $15/$6A,
 * places pixel data into bank 5 pages (10-11) via MMU, respecting the hardware
 * memory split ($4000-$57FF top 48 lines + $6000-$77FF bottom 48 lines).
 * Outputs .nex via SAVENEX.
 *
 * @param {Uint8Array} data - Raw 12288-byte pixel data (128×96 row-major)
 * @param {string} baseName - Base filename for SAVENEX output
 * @param {boolean} embedData - Embed pixel data as DB lines (true) or INCBIN (false)
 * @returns {{asm: string}|null} Complete ASM source code or null on error
 */
function generateLoresAsm(data, baseName, embedData) {
  if (!data || data.length < 12288) return null;

  // LoRes: 128×96, 8bpp, 256-color default ULA palette (RGB332→RGB333)
  // Memory layout: bank 5 = pages 10-11
  //   Top 48 lines:    $4000-$57FF (6144 bytes) — page 10 at $4000
  //   Bottom 48 lines: $6000-$77FF (6144 bytes) — page 11 at $6000
  //   Gap $5800-$5FFF (2048 bytes, unused by LoRes)

  const HALF = 6144;   // 48 * 128 = 6144 bytes per half
  const GAP = 2048;    // $5800-$5FFF padding

  // Default RGB332→RGB333 identity palette (256 entries, 2 bytes each)
  const palette = generateRgb332PaletteBytes(256);

  const asm = [];

  // === Header ===
  asm.push('; ============================================================================');
  asm.push('; Next LoRes viewer \u2014 ZX Spectrum Next (128\u00d796, 256-color)');
  asm.push('; Generated by SpectraLab v' + APP_VERSION);
  asm.push('; sjasmplus compatible source \u2014 builds .nex via SAVENEX');
  asm.push(';');
  asm.push('; LoRes mode 128\u00d796 8bpp, 256 ULA palette entries');
  asm.push('; Pixel data placed into bank 5 (pages 10-11) at assembly time');
  asm.push('; Top 48 lines at $4000-$57FF, bottom 48 at $6000-$77FF');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('    DEVICE ZXSPECTRUMNEXT');
  asm.push('    ORG $8000');
  asm.push('');

  // === Code ===
  asm.push('; ============================================================================');
  asm.push('; Initialization');
  asm.push('; ============================================================================');
  asm.push('Start:');
  asm.push('    DI');
  asm.push('    NEXTREG $07,3              ; 28 MHz');
  asm.push('');
  asm.push('    ; Program ULA palette (256 entries) for LoRes');
  asm.push('    NEXTREG $43,$00            ; Select ULA first palette, auto-increment');
  asm.push('    NEXTREG $40,0              ; Start at palette index 0');
  asm.push('    LD HL,PaletteData');
  asm.push('    LD B,0                     ; 256 entries (B=0 wraps)');
  asm.push('SetPalette:');
  asm.push('    LD A,(HL)');
  asm.push('    INC HL');
  asm.push('    NEXTREG $44,A              ; Write 8-bit color value (RRRGGGBB)');
  asm.push('    LD A,(HL)');
  asm.push('    INC HL');
  asm.push('    NEXTREG $44,A              ; Write 9th bit (blue LSB)');
  asm.push('    DJNZ SetPalette');
  asm.push('');

  // === Enable LoRes mode ===
  asm.push('    ; Enable LoRes mode, disable Layer 2');
  asm.push('    NEXTREG $15,$80            ; Reg $15 bit 7 = enable LoRes');
  asm.push('    NEXTREG $69,0              ; ULA palette offset = 0');
  asm.push('    NEXTREG $6A,0              ; LoRes X scroll = 0');
  asm.push('    NEXTREG $6B,0              ; LoRes Y scroll = 0');
  asm.push('');
  asm.push('    ; Disable Layer 2 (may be active from NEX loader/emulator default)');
  asm.push('    LD BC,$123B');
  asm.push('    XOR A');
  asm.push('    OUT (C),A');
  asm.push('');
  asm.push('    ; Set LoRes clip window (uses ULA clip register $1A)');
  asm.push('    ; Coordinates are in ULA-equivalent pixels (0-255 X, 0-191 Y)');
  asm.push('    NEXTREG $1C,2              ; Reset ULA/LoRes clip index (bit 1)');
  asm.push('    NEXTREG $1A,0              ; X1 = 0');
  asm.push('    NEXTREG $1A,255            ; X2 = 255');
  asm.push('    NEXTREG $1A,0              ; Y1 = 0');
  asm.push('    NEXTREG $1A,191            ; Y2 = 191');
  asm.push('');

  // === Black border ===
  asm.push('    ; Black border');
  asm.push('    NEXTREG $0E,0              ; Global transparency fallback = black');
  asm.push('    XOR A');
  asm.push('    OUT ($FE),A');
  asm.push('');

  // === Halt loop ===
  asm.push('    EI');
  asm.push('Halt:');
  asm.push('    HALT');
  asm.push('    JR Halt');
  asm.push('');

  // === Palette data (always embedded — small) ===
  asm.push('; ============================================================================');
  asm.push('; Palette data (512 bytes)');
  asm.push('; ============================================================================');
  asm.push('PaletteData:');
  asm.push(formatDbLines(palette, 16));
  asm.push('');

  // === Pixel data — placed into bank 5 pages via MMU ===
  asm.push('; ============================================================================');
  asm.push('; Pixel data \u2014 bank 5 (pages 10-11) via MMU');
  asm.push('; Top 48 lines: $4000-$57FF, gap $5800-$5FFF, bottom 48: $6000-$77FF');
  asm.push('; ============================================================================');
  asm.push('');

  // Map pages 10-11 into slots 2-3 ($4000-$7FFF)
  asm.push('    MMU 2 3,10                 ; Pages 10-11 into slots 2-3 ($4000-$7FFF)');
  asm.push('    ORG $4000');

  // Top 48 lines: 6144 bytes at $4000-$57FF
  if (embedData) {
    const topData = Array.from(data.slice(0, HALF));
    asm.push(formatDbLines(topData, 16));
  } else {
    asm.push('    INCBIN "' + baseName + '.slr",0,' + HALF);
  }

  // Gap: 2048 bytes of padding at $5800-$5FFF
  asm.push('    DS ' + GAP + ',0              ; $5800-$5FFF padding (not used by LoRes)');

  // Bottom 48 lines: 6144 bytes at $6000-$77FF
  if (embedData) {
    const bottomData = Array.from(data.slice(HALF, HALF * 2));
    asm.push(formatDbLines(bottomData, 16));
  } else {
    asm.push('    INCBIN "' + baseName + '.slr",' + HALF + ',' + HALF);
  }

  asm.push('');

  // === SAVENEX ===
  asm.push('; ============================================================================');
  asm.push('; Build .nex file');
  asm.push('; ============================================================================');
  asm.push('    SAVENEX OPEN "' + baseName + '.nex",Start,$FF40');
  asm.push('    SAVENEX CORE 3,1,5          ; Next core 3.1.5 minimum');
  asm.push('    SAVENEX CFG 0               ; No border color');
  asm.push('    SAVENEX AUTO                ; Auto-include all changed pages');
  asm.push('    SAVENEX CLOSE');
  asm.push('');

  return { asm: asm.join('\n') };
}

/**
 * Exports LoRes picture as sjasmplus ASM source file.
 */
function exportLoresAsm() {
  if (currentFormat !== FORMAT.LORES) {
    alert('Export ASM is only available for LoRes format.');
    return;
  }
  if (!screenData || screenData.length < 12288) {
    alert('No data loaded.');
    return;
  }

  runAsmExport('lores', (baseName, embed) => generateLoresAsm(screenData.slice(0, 12288), baseName, embed));
}

/**
 * Generates sjasmplus-compatible ASM source for ZX Spectrum Next LoRes Radastan display.
 * Radastan mode: 128×96, 4bpp (16 colors), register $6A bit 5 enables it.
 * Hardware reads 128 bytes/row in the same split layout as 8bpp LoRes.
 * Each source pixel is doubled horizontally: nibble N → byte (N<<4)|N.
 * The 16-entry ULA palette (RGB332→RGB333) is programmed via NEXTREG before
 * enabling the display, using the same $43/$40/$44 sequence as the 8bpp export.
 *
 * @param {Uint8Array} data - Raw 6144-byte packed pixel data (128×96, 4bpp row-major)
 * @param {string} baseName - Base filename for SAVENEX output
 * @param {boolean} embedData - Embed pixel data as DB lines (true) or INCBIN (false)
 * @param {number[][]|null} [resolvedPalette] - 16-entry [r,g,b] palette (null = default RGB332)
 * @returns {{asm: string}|null} Complete ASM source code or null on error
 */
function generateLoresRadAsm(data, baseName, embedData, resolvedPalette) {
  if (!data || data.length < 6144) return null;

  // Radastan: 128×96, 4bpp, 16 ULA palette entries
  // Reg $6A: bit 5 = Radastan enable, bits 3-0 = palette offset
  //
  // Hardware memory layout (same as 8bpp LoRes, 128 bytes/row):
  //   Top 48 lines:    $4000-$57FF (6144 bytes) — page 10
  //   Bottom 48 lines: $6000-$77FF (6144 bytes) — page 11
  //   Gap $5800-$5FFF (2048 bytes, unused)
  //
  // In 4bpp: each 128-byte row → 256 pixels. Source .rad has 64 bytes/row
  // (128 pixels). We double each pixel: nibble N → byte (N<<4)|N.

  const HALF = 6144;   // 48 * 128 = 6144 bytes per hardware half
  const GAP = 2048;    // $5800-$5FFF padding
  const SRC_BPR = 64;  // source bytes per row (packed 4bpp)

  // Pixel-double: 64 bytes/row → 128 bytes/row
  // Each source nibble becomes both nibbles of one output byte
  function pixelDoubleRow(srcData, srcRowOffset) {
    const row = new Array(128);
    for (let x = 0; x < 128; x++) {
      const srcByte = srcData[srcRowOffset + (x >> 1)] || 0;
      const nibble = (x & 1) === 0 ? (srcByte >> 4) & 0x0F : srcByte & 0x0F;
      row[x] = (nibble << 4) | nibble;   // double: both nibbles same
    }
    return row;
  }

  // Build top and bottom halves with pixel-doubled rows
  const topData = [];
  for (let y = 0; y < 48; y++) {
    const row = pixelDoubleRow(data, y * SRC_BPR);
    for (let i = 0; i < 128; i++) topData.push(row[i]);
  }
  const bottomData = [];
  for (let y = 48; y < 96; y++) {
    const row = pixelDoubleRow(data, y * SRC_BPR);
    for (let i = 0; i < 128; i++) bottomData.push(row[i]);
  }

  // Generate 16-entry RGB333 palette (2 bytes per entry, 32 bytes total)
  // Use resolved palette if available (from file with embedded palette), otherwise default
  const palette = [];
  for (let i = 0; i < 16; i++) {
    let r3, g3, b3;
    if (resolvedPalette && resolvedPalette[i]) {
      // Convert [r,g,b] (0-255) back to 3-bit components
      r3 = Math.round(resolvedPalette[i][0] * 7 / 255);
      g3 = Math.round(resolvedPalette[i][1] * 7 / 255);
      b3 = Math.round(resolvedPalette[i][2] * 7 / 255);
    } else {
      // Default RGB332 identity: first 16 entries
      r3 = (i >> 5) & 7;
      g3 = (i >> 2) & 7;
      const b2 = i & 3;
      b3 = (b2 << 1) | (b2 >> 1);
    }
    const byte1 = (r3 << 5) | (g3 << 2) | (b3 >> 1);
    const byte2 = b3 & 1;
    palette.push(byte1, byte2);
  }

  const asm = [];

  // === Header ===
  asm.push('; ============================================================================');
  asm.push('; Next LoRes Radastan viewer \u2014 ZX Spectrum Next (128\u00d796, 16-color 4bpp)');
  asm.push('; Generated by SpectraLab v' + APP_VERSION);
  asm.push('; sjasmplus compatible source \u2014 builds .nex via SAVENEX');
  asm.push(';');
  asm.push('; Radastan mode 128\u00d796 4bpp, 16 ULA palette entries (RGB332)');
  asm.push('; Each source pixel doubled horizontally (128 bytes/row in hardware)');
  asm.push('; Palette programmed via NEXTREG $43/$40/$44 before enabling display');
  asm.push('; Pixel data placed into bank 5 (pages 10-11) at assembly time');
  asm.push('; Top 48 lines at $4000-$57FF, bottom 48 at $6000-$77FF');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('    DEVICE ZXSPECTRUMNEXT');
  asm.push('    ORG $8000');
  asm.push('');

  // === Code ===
  asm.push('; ============================================================================');
  asm.push('; Initialization');
  asm.push('; ============================================================================');
  asm.push('Start:');
  asm.push('    DI');
  asm.push('    NEXTREG $07,3              ; 28 MHz');
  asm.push('');

  // === Program palette BEFORE enabling display mode ===
  asm.push('    ; Program ULA palette (16 entries) for Radastan');
  asm.push('    NEXTREG $43,$00            ; Select ULA first palette, auto-increment');
  asm.push('    NEXTREG $40,0              ; Start at palette index 0');
  asm.push('    LD HL,PaletteData');
  asm.push('    LD B,16                    ; 16 entries');
  asm.push('SetPalette:');
  asm.push('    LD A,(HL)');
  asm.push('    INC HL');
  asm.push('    NEXTREG $44,A              ; Write 8-bit color value (RRRGGGBB)');
  asm.push('    LD A,(HL)');
  asm.push('    INC HL');
  asm.push('    NEXTREG $44,A              ; Write 9th bit (blue LSB)');
  asm.push('    DJNZ SetPalette');
  asm.push('');

  // === Enable LoRes Radastan mode ===
  asm.push('    ; Enable LoRes Radastan mode');
  asm.push('    NEXTREG $15,$80            ; Reg $15 bit 7 = enable LoRes');
  asm.push('    NEXTREG $69,0              ; ULA palette offset = 0');
  asm.push('    NEXTREG $6A,$20            ; Reg $6A bit 5 = Radastan 4bpp');
  asm.push('    NEXTREG $6B,0              ; LoRes Y scroll = 0');
  asm.push('');
  asm.push('    ; Disable Layer 2 (may be active from NEX loader/emulator default)');
  asm.push('    LD BC,$123B');
  asm.push('    XOR A');
  asm.push('    OUT (C),A');
  asm.push('');

  // === Clip window ===
  asm.push('    ; Set LoRes clip window (uses ULA clip register $1A)');
  asm.push('    ; Coordinates are in ULA-equivalent pixels (0-255 X, 0-191 Y)');
  asm.push('    NEXTREG $1C,2              ; Reset ULA/LoRes clip index (bit 1)');
  asm.push('    NEXTREG $1A,0              ; X1 = 0');
  asm.push('    NEXTREG $1A,255            ; X2 = 255');
  asm.push('    NEXTREG $1A,0              ; Y1 = 0');
  asm.push('    NEXTREG $1A,191            ; Y2 = 191');
  asm.push('');

  // === Black border ===
  asm.push('    ; Black border');
  asm.push('    NEXTREG $0E,0              ; Global transparency fallback = black');
  asm.push('    XOR A');
  asm.push('    OUT ($FE),A');
  asm.push('');

  // === Halt loop ===
  asm.push('    EI');
  asm.push('Halt:');
  asm.push('    HALT');
  asm.push('    JR Halt');
  asm.push('');

  // === Palette data (always embedded — 32 bytes) ===
  asm.push('; ============================================================================');
  asm.push('; Palette data (32 bytes \u2014 16 entries, RGB333, 2 bytes each)');
  asm.push('; ============================================================================');
  asm.push('PaletteData:');
  asm.push(formatDbLines(palette, 16));
  asm.push('');

  // === Pixel data — placed into bank 5 pages via MMU ===
  asm.push('; ============================================================================');
  asm.push('; Pixel data \u2014 bank 5 (pages 10-11) via MMU');
  asm.push('; Pixel-doubled: 128 bytes/row (each source pixel appears twice)');
  asm.push('; Top 48 lines: $4000-$57FF, gap $5800-$5FFF, bottom 48: $6000-$77FF');
  asm.push('; ============================================================================');
  asm.push('');

  // Map pages 10-11 into slots 2-3 ($4000-$7FFF)
  asm.push('    MMU 2 3,10                 ; Pages 10-11 into slots 2-3 ($4000-$7FFF)');
  asm.push('    ORG $4000');

  // Top 48 lines: 6144 bytes at $4000-$57FF (pixel-doubled)
  asm.push(formatDbLines(topData, 16));

  // Gap: 2048 bytes of padding at $5800-$5FFF
  asm.push('    DS ' + GAP + ',0              ; $5800-$5FFF padding (not used by LoRes)');

  // Bottom 48 lines: 6144 bytes at $6000-$77FF (pixel-doubled)
  asm.push(formatDbLines(bottomData, 16));

  asm.push('');

  // === SAVENEX ===
  asm.push('; ============================================================================');
  asm.push('; Build .nex file');
  asm.push('; ============================================================================');
  asm.push('    SAVENEX OPEN "' + baseName + '.nex",Start,$FF40');
  asm.push('    SAVENEX CORE 3,1,5          ; Next core 3.1.5 minimum');
  asm.push('    SAVENEX CFG 0               ; No border color');
  asm.push('    SAVENEX AUTO                ; Auto-include all changed pages');
  asm.push('    SAVENEX CLOSE');
  asm.push('');

  return { asm: asm.join('\n') };
}

/**
 * Exports LoRes Radastan picture as sjasmplus ASM source file.
 */
function exportLoresRadAsm() {
  if (currentFormat !== FORMAT.LORES_RAD) {
    alert('Export ASM is only available for LoRes Radastan format.');
    return;
  }
  if (!screenData || screenData.length < 6144) {
    alert('No data loaded.');
    return;
  }

  const pal = (typeof nxiResolvedPalette !== 'undefined' && nxiResolvedPalette && nxiResolvedPalette.length >= 16)
    ? nxiResolvedPalette : null;
  runAsmExport('radastan', (baseName, embed) => generateLoresRadAsm(screenData.slice(0, 6144), baseName, embed, pal));
}
