// @ts-check
"use strict";
// ============================================================================
// Next Layer 2 ASM Export — sjasmplus SAVENEX source for NXI/SL2 pictures
// ============================================================================

/**
 * Generates sjasmplus-compatible ASM source for ZX Spectrum Next Layer 2 display.
 * Programs the palette via NEXTREG, enables Layer 2, outputs .nex via SAVENEX.
 * Pixel data is placed directly into L2 bank pages at assembly time — the NEX
 * loader maps them automatically, so no runtime pixel copying is needed.
 *
 * @param {Uint8Array} data - Full file data (NXI with palette or SL2 raw)
 * @param {string} baseName - Base filename for SAVENEX output
 * @param {boolean} embedData - Embed pixel data as DB lines (true) or INCBIN (false)
 * @param {string} format - FORMAT.NXI or FORMAT.SL2
 * @param {string} mode - '256x192', '320x256', or '640x256'
 * @returns {{asm: string}|null} Complete ASM source code or null on error
 */
function generateNextL2Asm(data, baseName, embedData, format, mode) {
  if (!data || data.length === 0) return null;

  // --- Mode parameters ---
  let modeVal, palEntries, palSize, pixelSize, pageCount, modeComment, clipX2, clipY2;
  if (mode === '320x256') {
    modeVal = 0x10;       // reg $70 bits 5-4 = 01
    palEntries = 256;
    palSize = 512;
    pixelSize = 81920;    // 320*256 = 80KB
    pageCount = 10;       // pages 16-25
    modeComment = '320\u00d7256 8bpp';
    clipX2 = 159;         // doubled coords: 159*2+1 = 319
    clipY2 = 255;
  } else if (mode === '640x256') {
    modeVal = 0x20;       // reg $70 bits 5-4 = 10
    palEntries = 16;
    palSize = 32;
    pixelSize = 81920;    // 640*256/2 = 80KB (4bpp)
    pageCount = 10;       // pages 16-25
    modeComment = '640\u00d7256 4bpp';
    clipX2 = 159;         // quadrupled coords: 159*4+3 = 639
    clipY2 = 255;
  } else {
    modeVal = 0x00;       // reg $70 bits 5-4 = 00
    palEntries = 256;
    palSize = 512;
    pixelSize = 49152;    // 256*192 = 48KB
    pageCount = 6;        // pages 16-21
    modeComment = '256\u00d7192 8bpp';
    clipX2 = 255;         // pixel coords
    clipY2 = 191;
  }

  // --- Extract palette ---
  let palette;
  if (format === FORMAT.NXI) {
    // NXI: palette is at the start of the file
    const rawPalSize = mode === '640x256' ? NXI.PALETTE_SIZE_4BPP : NXI.PALETTE_SIZE;
    palette = Array.from(data.slice(0, rawPalSize));
  } else {
    // SL2: no embedded palette — generate default RGB332->RGB333 identity
    if (mode === '640x256') {
      // 4bpp: first 16 entries of RGB332→RGB333 identity palette (matches viewer)
      palette = generateRgb332PaletteBytes(16);
    } else {
      // 8bpp: 256 entries, 2 bytes each — identity RGB332→RGB333
      palette = generateRgb332PaletteBytes(256);
    }
  }

  // --- Extract pixel data offset ---
  let pixelOffset;
  if (format === FORMAT.NXI) {
    pixelOffset = mode === '640x256' ? NXI.PIXEL_OFFSET_4BPP : NXI.PIXEL_OFFSET;
  } else {
    // SL2: may have 128-byte header for 256x192
    if (mode === '256x192' && data.length === SL2.HEADER_SIZE) {
      pixelOffset = SL2.HEADER_OFFSET;
    } else {
      pixelOffset = 0;
    }
  }

  const asm = [];

  // === Header ===
  asm.push('; ============================================================================');
  asm.push('; Next Layer 2 viewer \u2014 ZX Spectrum Next (' + modeComment + ')');
  asm.push('; Generated by SpectraLab v' + APP_VERSION);
  asm.push('; sjasmplus compatible source \u2014 builds .nex via SAVENEX');
  asm.push(';');
  asm.push('; Layer 2 mode ' + modeComment + ', ' + palEntries + ' palette entries');
  asm.push('; Pixel data placed into L2 bank pages at assembly time (no runtime copy)');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('    DEVICE ZXSPECTRUMNEXT');
  asm.push('    ORG $8000');
  asm.push('');

  // === Code ===
  asm.push('; ============================================================================');
  asm.push('; Initialization');
  asm.push('; ============================================================================');
  asm.push('Start:');
  asm.push('    DI');
  asm.push('    NEXTREG $07,3              ; 28 MHz');
  asm.push('    NEXTREG $12,8              ; Layer 2 bank = 8 (pages 16+, default)');
  asm.push('    NEXTREG $70,$' + modeVal.toString(16).toUpperCase().padStart(2, '0') + '            ; Layer 2 mode: ' + modeComment);
  asm.push('');
  asm.push('    ; Set Layer 2 clip window');
  asm.push('    NEXTREG $1C,1              ; Reset Layer 2 clip index (bit 0)');
  asm.push('    NEXTREG $18,0              ; X1 = 0');
  asm.push('    NEXTREG $18,' + clipX2 + '           ; X2 = ' + clipX2);
  asm.push('    NEXTREG $18,0              ; Y1 = 0');
  asm.push('    NEXTREG $18,' + clipY2 + '           ; Y2 = ' + clipY2);
  asm.push('');

  // === Program palette ===
  asm.push('    ; Program Layer 2 palette (' + palEntries + ' entries)');
  asm.push('    NEXTREG $43,$10            ; Select Layer 2 first palette, auto-increment');
  asm.push('    NEXTREG $40,0              ; Start at palette index 0');
  asm.push('    LD HL,PaletteData');
  asm.push('    LD B,' + (palEntries & 0xFF));
  asm.push('SetPalette:');
  asm.push('    LD A,(HL)');
  asm.push('    INC HL');
  asm.push('    NEXTREG $44,A              ; Write 8-bit color value (RRRGGGBB)');
  asm.push('    LD A,(HL)');
  asm.push('    INC HL');
  asm.push('    NEXTREG $44,A              ; Write 9th bit (blue LSB)');
  asm.push('    DJNZ SetPalette');
  asm.push('');

  // === Enable Layer 2 ===
  asm.push('    ; Enable Layer 2');
  asm.push('    LD BC,$123B');
  asm.push('    LD A,2                     ; Bit 1 = Layer 2 visible');
  asm.push('    OUT (C),A');
  asm.push('');

  // === Black border ===
  asm.push('    ; Black border');
  asm.push('    NEXTREG $0E,0              ; Global transparency fallback = black');
  asm.push('    XOR A');
  asm.push('    OUT ($FE),A');
  asm.push('');

  // === Halt loop ===
  asm.push('    EI');
  asm.push('Halt:');
  asm.push('    HALT');
  asm.push('    JR Halt');
  asm.push('');

  // === Palette data (always embedded — small) ===
  asm.push('; ============================================================================');
  asm.push('; Palette data (' + palette.length + ' bytes)');
  asm.push('; ============================================================================');
  asm.push('PaletteData:');
  asm.push(formatDbLines(palette, 16));
  asm.push('');

  // === Pixel data — placed into L2 pages via MMU ===
  asm.push('; ============================================================================');
  asm.push('; Pixel data \u2014 mapped into Layer 2 bank pages via MMU');
  asm.push('; ============================================================================');

  const CHUNK_SIZE = 16384; // 16KB per MMU pair (slots 0-1)
  const chunkCount = Math.ceil(pixelSize / CHUNK_SIZE);
  const startPage = 16; // L2 bank 8 -> pages 16,17,18,...

  for (let i = 0; i < chunkCount; i++) {
    const page = startPage + i * 2;
    const chunkOffset = i * CHUNK_SIZE;
    const chunkLen = Math.min(CHUNK_SIZE, pixelSize - chunkOffset);

    asm.push('');
    asm.push('    MMU 0 1,' + page + '              ; Pages ' + page + '-' + (page + 1) + ' into slots 0-1');
    asm.push('    ORG $0000');

    if (embedData) {
      const chunkData = Array.from(data.slice(pixelOffset + chunkOffset, pixelOffset + chunkOffset + chunkLen));
      asm.push(formatDbLines(chunkData, 16));
    } else {
      const ext = format === FORMAT.NXI ? 'nxi' : 'sl2';
      asm.push('    INCBIN "' + baseName + '.' + ext + '",' + (pixelOffset + chunkOffset) + ',' + chunkLen);
    }
  }

  asm.push('');

  // === SAVENEX ===
  asm.push('; ============================================================================');
  asm.push('; Build .nex file');
  asm.push('; ============================================================================');
  asm.push('    SAVENEX OPEN "' + baseName + '.nex",Start,$FF40');
  asm.push('    SAVENEX CORE 3,1,5          ; Next core 3.1.5 minimum');
  asm.push('    SAVENEX CFG 0               ; No border color');
  asm.push('    SAVENEX AUTO                ; Auto-include all changed pages');
  asm.push('    SAVENEX CLOSE');
  asm.push('');

  return { asm: asm.join('\n') };
}

/**
 * Exports NXI/SL2 picture as sjasmplus ASM source file.
 */
function exportNextL2Asm() {
  if (currentFormat !== FORMAT.NXI && currentFormat !== FORMAT.SL2) {
    alert('Export ASM is only available for NXI/SL2 formats.');
    return;
  }
  if (!screenData || screenData.length === 0) {
    alert('No data loaded.');
    return;
  }

  runAsmExport('layer2', (baseName, embed) =>
    generateNextL2Asm(screenData, baseName, embed, currentFormat, nxiLayer2Mode));
}
