// ============================================================================
// ULA+ ASM Export — sjasmplus-compatible ASM source for ULA+ pictures
// ============================================================================

/**
 * Generates sjasmplus-compatible ASM source for ULA+ display.
 * Programs the 64-entry palette via I/O ports, copies screen data, enables ULA+ mode.
 * @param {Uint8Array} ulaPlusData - 6976 bytes (6912 SCR + 64 palette)
 * @param {string} baseName - Base filename for SAVESNA output
 * @param {boolean} embedData - Embed data as DB lines (true) or use INCBIN (false)
 * @returns {{asm: string}|null} Complete ASM source code or null on error
 */
function generateUlaPlusAsm(ulaPlusData, baseName = 'ulaplus', embedData = true) {
  if (!ulaPlusData || ulaPlusData.length < ULAPLUS.TOTAL_SIZE) return null;

  const scrData = Array.from(ulaPlusData.slice(0, 6912));
  const palette = Array.from(ulaPlusData.slice(ULAPLUS.PALETTE_OFFSET, ULAPLUS.PALETTE_OFFSET + ULAPLUS.PALETTE_SIZE));

  const asm = [];

  // === Header ===
  asm.push('; ============================================================================');
  asm.push('; ULA+ viewer — ZX Spectrum with ULA+ extension');
  asm.push('; Generated by SpectraLab v' + APP_VERSION);
  asm.push('; sjasmplus compatible source');
  asm.push(';');
  asm.push('; ULA+ provides 64-color palette in GRB332 format (4 CLUTs × 16 colors)');
  asm.push('; Register port: #BF3B (select palette index 0-63, or 64 for mode register)');
  asm.push('; Data port:     #FF3B (write GRB332 color value, or mode flags)');
  asm.push('; Mode register (index 64): bit 0 = palette mode enable');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('    DEVICE ZXSPECTRUM48');
  asm.push('    ORG #8000');
  asm.push('');

  // === Constants ===
  asm.push('ULAPLUS_REG  EQU #BF3B       ; Register select port');
  asm.push('ULAPLUS_DATA EQU #FF3B       ; Data read/write port');
  asm.push('');

  // === Initialization ===
  asm.push('; ============================================================================');
  asm.push('; Initialization');
  asm.push('; ============================================================================');
  asm.push('Start:');
  asm.push('    DI');
  asm.push('');

  // === Copy screen data ===
  asm.push('    ; Copy screen data to #4000 (6912 bytes: 6144 bitmap + 768 attributes)');
  asm.push('    LD HL,ScrData');
  asm.push('    LD DE,#4000');
  asm.push('    LD BC,6912');
  asm.push('    LDIR');
  asm.push('');

  // === Program palette and enable ULA+ ===
  asm.push('    ; Program ULA+ palette (64 entries)');
  asm.push('    ; C=#3B shared by both ports, B selects: #BF=register, #FF=data');
  asm.push('    LD HL,PaletteData');
  asm.push('    LD C,#3B');
  asm.push('    LD D,#BF                  ; Register port high byte');
  asm.push('    LD E,0                    ; Palette index');
  asm.push('SetPalette:');
  asm.push('    LD B,D                    ; BC = #BF3B (register port)');
  asm.push('    OUT (C),E                 ; Select palette index');
  asm.push('    LD A,(HL)                 ; Read GRB332 color');
  asm.push('    LD B,#FF                  ; BC = #FF3B (data port)');
  asm.push('    OUT (C),A                 ; Write color value');
  asm.push('    INC HL');
  asm.push('    INC E');
  asm.push('    BIT 6,E                   ; E == 64?');
  asm.push('    JR Z,SetPalette');
  asm.push('');
  asm.push('    ; Enable ULA+ palette mode (E already = 64 = mode register)');
  asm.push('    LD B,D                    ; BC = #BF3B');
  asm.push('    OUT (C),E                 ; Select mode register (64)');
  asm.push('    LD B,#FF                  ; BC = #FF3B');
  asm.push('    LD A,1                    ; Bit 0 = enable palette mode');
  asm.push('    OUT (C),A');
  asm.push('');

  // === Set border ===
  asm.push('    ; Set border to black');
  asm.push('    XOR A');
  asm.push('    OUT (#FE),A');
  asm.push('');

  // === Halt loop ===
  asm.push('    EI');
  asm.push('Halt:');
  asm.push('    HALT');
  asm.push('    JR Halt');
  asm.push('');

  // === Data section ===
  asm.push('; ============================================================================');
  asm.push('; Data');
  asm.push('; ============================================================================');
  asm.push('');
  asm.push('ScrData:                     ; 6912 bytes (bitmap + attributes)');
  if (embedData) {
    asm.push(formatDbLines(scrData, 16));
  } else {
    asm.push(`    INCBIN "${baseName}.scr", 0, 6912`);
  }
  asm.push('');

  // Palette is always embedded (only 64 bytes, not worth INCBIN)
  asm.push('PaletteData:                 ; 64 bytes (GRB332)');
  asm.push(formatDbLines(palette, 16));
  asm.push('');
  asm.push('    SAVESNA "' + baseName + '.sna",Start');
  asm.push('');

  return { asm: asm.join('\n') };
}

/**
 * Exports ULA+ picture as sjasmplus ASM source file.
 */
function exportUlaPlusAsm() {
  if (currentFormat !== FORMAT.SCR_ULAPLUS || !screenData || screenData.length < ULAPLUS.TOTAL_SIZE) {
    alert('Export ASM is only available for ULA+ format.');
    return;
  }

  runAsmExport('ulaplus', (baseName, embed) => generateUlaPlusAsm(screenData, baseName, embed));
}
